### ISSUE TITLE
Conda Releases

### ISSUE THREAD

**Issue by quasiben** [rapidsai/jupyterlab-nvdashboard#56] opened 2020-04-20 18:33 UTC
We need new conda releases on rapidsai-nightly and conda-forge.  Latest conda releases are  `0.1.11`

**Comment by jakirkham** [comment] 2020-04-20 19:16
On `rapidsai`, it is [up-to-date]( https://anaconda.org/rapidsai/jupyterlab-nvdashboard/files?version=0.2.1 ).

Not sure how `rapidsai-nightly` is updated. Maybe someone from OPS can comment (cc @raydouglass)? 🙂

The `jupyterlab-nvdashboard` feedstock has [PRs open to update]( https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pulls ). So it is just a matter of someone working to integrate those.

**Comment by raydouglass** [comment] 2020-04-20 20:22
I've released a v0.3.0 nightly to rapidsai-nightly, pypi, and npm.

**Comment by owenlamont** [comment] 2020-06-01 06:54
Hi @raydouglass - sorry I tried to jump in and work on the conda-forge [PR]( https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pull/6) but I hadn't properly checked the other issues here until now. I didn't know there was a rapidsai conda channel and I also see the [meta.yaml](https://github.com/rapidsai/jupyterlab-nvdashboard/blob/branch-0.4/conda/recipes/jupyterlab-nvdashboard/meta.yaml) in this repo which I didn't try to keep consistent with my PR. I guess conda-forge recipes work differently but I assume the requirements should be consistent between both?

Happy to help if I can and I'm not getting in your way. Is the rapidsai channel meta.yaml the one included in this repository?

**Comment by raydouglass** [comment] 2020-06-01 14:59
> Is the rapidsai channel meta.yaml the one included in this repository?

Yes, that's correct.

**Comment by owenlamont** [comment] 2020-06-02 14:39
Hi @raydouglass, @jakirkham - I ran into an issue with my conda-forge recipe and I was wondering if you can advise on the best way to resolve it. Unlike the rapidsai recipe the conda-forge recipe [meta.yaml](https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/blob/master/recipe/meta.yaml) automatically installs the labextension. That is nice but the issue is that the recipe explicitly sets the version number of the labextension to match that of the conda package. 

That is problematic because if you install version 0.3.1 of the conda package the labextension will be broken if the user is using jupyterlab 1. I see two possible options and I was wondering which you both think is better:

1. I remove the explicit labextension version number from the conda-forge meta.yaml and trust the labextension to install the highest version supported by the jupyter lab the user has installed (that is how it works now with the rapidsai recipe - except the user has to manually install the labextension).
2. I explicitly restrict the conda-forge recipe to require jupyterlab >=2 (which is what I currently have in my [PR](https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pull/6)) and maybe I need to add a seperate conda-forge recipe for version 0.3.0 which has a jupyterlab <2 requirement.

I'm not sure what you think is better or whether there is some other options I'm overlooking.

**Comment by owenlamont** [comment] 2020-06-04 16:11
I've done a bit of research into how other jupyter lab extension python packages install and keep their node packages in sync. I found the following packages install their lab extensions automatically:

* [ipyevents](https://github.com/mwcraig/ipyevents)
* [jupyter-threejs](https://github.com/jupyter-widgets/pythreejs)
* [pywwt](https://github.com/WorldWideTelescope/pywwt)
* [jupyter-matplotlib](https://github.com/matplotlib/ipympl)
* [jupyter-vue](https://github.com/mariobuikhuizen/ipyvue)
* [jupyter-leaflet](https://github.com/jupyter-widgets/ipyleaflet)
* [ipycanvas](https://github.com/martinRenou/ipycanvas)
* [nbdime](https://github.com/jupyter/nbdime)
* [ipyvolume](https://github.com/maartenbreddels/ipyvolume/blob/master/setup.py)

Interestingly I couldn't find any other lab extensions that call jupyter labextension install from their meta.yml or associated scripts. I guess they wanted a way that isn't restricted just to conda recipes - I don't know if there's any other reason not to do that. I haven't thoroughly looked but most seem to implement the lab extension install in their setup.py logic.

Looks like a relatively big job and the topic for a different issue and PR.

**Comment by jakirkham** [comment] 2020-06-04 19:03
Yeah I asked about this once in issue ( https://github.com/conda-forge/ipympl-feedstock/issues/26 ). It sounded like people weren't sure whether this should be done generally. Perhaps it would be worthwhile to revisit that discussion?

**Comment by jacobtomlinson** [comment] 2020-06-05 09:11
For the record, I'm happy to remove the `jupyter labextension install` from the recipe. It was an experiment to see if it was possible more than anything.

**Comment by owenlamont** [comment] 2020-06-06 14:37
Interesting discussion on the ipympl feedstock. I do like the convenience of conda installing the labextension itself. I hadn't thought about the complexity of multiple kernels in different environments though (I usually always use local environment kernels). I've left the labextension install step in the conda-forge recipe for now... but happy to go with the consensus if anyone wants to change that.

**Comment by jakirkham** [comment] 2020-06-08 19:16
Leaving it seems fine to me, but no strong feelings.

**Comment by owenlamont** [comment] 2020-06-20 12:39
The conda-feedstock is updated now so we can close this issue I think...

**Comment by jakirkham** [comment] 2020-06-20 18:40
Thanks @owenlamont! 😀

**Closed by jakirkham** 2020-06-20 18:40 UTC

**Comment by jakirkham** [comment] 2020-10-07 19:56
FWIW there is some discussion about updating how JupyterLab extension Conda packages are built in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/761 ). This includes both general changes that are suggested as well as changes for JupyterLab 3.
