### ISSUE TITLE
 nothing showing up

### ISSUE THREAD

**Issue by misoinwoo** [rapidsai/jupyterlab-nvdashboard#136] opened 2022-09-07 06:29 UTC
hello

pip install jupyterlab-nvdashboard

Installation is complete.

But nothing shows up in GPU DASHBOARDS.

What is the problem?

![image](https://user-images.githubusercontent.com/113008551/188804849-9221c80f-7db8-4267-94ab-a66a1654d92b.png)

![image](https://user-images.githubusercontent.com/113008551/188804920-7113fd69-7c39-40f1-acf2-9bdec743567d.png)

How do I match the version?
![image](https://user-images.githubusercontent.com/113008551/188808079-e9b8b8ab-920d-440b-8e95-53ec89ff060e.png)

**Comment by jacobtomlinson** [comment] 2022-09-07 11:12
Duplicate of #24

**Closed by jacobtomlinson** 2022-09-07 11:12 UTC
