### ISSUE TITLE
Machine Resources 500 error

### ISSUE THREAD

**Issue by fabiosanger** [rapidsai/jupyterlab-nvdashboard#153] opened 2023-02-23 12:02 UTC
Hello,

Machine Resources, GPU Utilisation and GPU resources are returning 500 error

```
Config dir: /opt/conda/envs/rapids/etc/jupyter
    dask_labextension enabled
    - Validating dask_labextension...
      dask_labextension 5.3.0 OK
    jupyter_server_proxy enabled
    - Validating jupyter_server_proxy...
      jupyter_server_proxy  OK
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage 0.7.1 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
      jupyter_server_fileid 0.7.0 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
      jupyter_server_ydoc 0.6.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.6.1 OK
    jupyterlab_nvdashboard enabled
    - Validating jupyterlab_nvdashboard...
      jupyterlab_nvdashboard  OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.4.5 OK

Config dir: /usr/local/etc/jupyter

JupyterLab v3.6.1
/nfs/users/nfs_f/fg12/Custom/.local/share/jupyter/labextensions
        jupyterlab-plotly v5.13.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)

/opt/conda/envs/rapids/share/jupyter/labextensions
        dask-labextension v5.3.0 enabled OK (python, dask_labextension)
        jupyter-matplotlib v0.11.3 enabled OK
        jupyterlab-favorites v3.0.0 enabled OK (python, jupyterlab-favorites)
        jupyterlab-nvdashboard v0.7.0 enabled OK (python, jupyterlab_nvdashboard)
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-server/resource-usage v0.7.1 enabled OK (python, jupyter-resource-usage)
        @jupyterlab/server-proxy v3.2.2 enabled OK
        @pyviz/jupyterlab_pyviz v2.2.1 enabled OK (python, pyviz_comms)
```

![image](https://user-images.githubusercontent.com/118277438/220899824-2378b03c-5e8a-44df-b83f-8ef61e3f6120.png)
![image](https://user-images.githubusercontent.com/118277438/220899982-6f93dc37-359a-4e6a-87d4-35453f140800.png)

**Comment by jacobtomlinson** [comment] 2023-03-07 11:30
Duplicate of #114

**Closed by jacobtomlinson** 2023-03-07 11:30 UTC
