### ISSUE TITLE
Running on multiple machines?

### ISSUE THREAD

**Issue by jarednielsen** [rapidsai/jupyterlab-nvdashboard#45] opened 2020-02-20 02:26 UTC
Can I run this on multiple machines? I'm doing distributed training via Kubernetes across 8 different nodes, and seeing GPU utilization for all 64 GPUs in real-time would help diagnose communication bottlenecks and Horovod hanging. Any tips for how to tweak this for multi-node?

**Comment by jacobtomlinson** [comment] 2020-02-20 09:15
I'm going to close this as a duplicate of #34.

I'll also add some further context over on that issue.

**Closed by jacobtomlinson** 2020-02-20 09:15 UTC
